# Graphs depicting rate of blacklisting for liars given fixed lies

This file allows us to measure how many liars are blacklisted, depending on the choice of liars for a fixed set of lies.

There are multiple configurable variables (see below)

The generated data can be created by the graph_var_liars_test.go file.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#configs
lowerBoundLies = 1000  #lower bound on difference between true latency and lie told about it
upperBoundLies = 5000 #upper bound on difference between true latency and lie told about it
nbNodes = 100
nbLiars = 33
nbLiarCombinations = 100 #nb different combinations of liars chosen throughout test
randomLiars = False      #whether the liars are chosen randomly or within cluster
withSuspects = True      #activate enhanced blacklisting

random = "random_liars"
if not randomLiars:
    random = "clustered_liars"

filename = "test_" + \
    str(nbNodes) + "_nodes_" +\
    str(nbLiars) + "_liars" +\
    "_var_liars_distance_" + str(upperBoundLies) +\
    "_" + random +\
    "_" + str(nbLiarCombinations) + "_combinations"

if withSuspects:
    filename += "_with_suspects"

In [3]:
data= pd.read_csv("data/" + filename + ".csv")

In [4]:
data

       node  is_liar  is_blacklisted   lie  cluster
0        N0     True            True  2308        0
1        N0     True            True  2540        0
2        N0     True            True  3071        0
3        N0     True            True  4974        0
4        N0     True            True  2315        0
5        N0     True            True  3556        0
6        N0     True            True  2353        0
7        N0     True            True  3061        0
8        N0     True            True  4828        0
9        N0     True            True  3823        0
10       N0     True            True  4775        0
11       N0     True            True  2527        0
12       N0     True            True  3116        0
13       N0     True            True  4248        0
14       N0     True            True  4492        0
15       N0     True            True  3266        0
16       N0     True            True  3841        0
17       N0     True            True  4435        0
18       N0     True            True  4378        0
19       N0     True            True  2169        0
20       N0     True            True  2403        0
21       N0     True            True  2402        0
22       N0     True            True  2621        0
23       N0     True            True  1117        0
24       N0     True            True  2537        0
25       N0     True            True  2642        0
26       N0     True            True  4617        0
27       N0     True            True  1392        0
28       N0     True            True  2191        0
29       N0     True            True  4999        0
...     ...      ...             ...   ...      ...
280570  N70    False           False     0       99
280571  N71    False           False     0       99
280572  N72    False           False     0       99
280573  N73    False           False     0       99
280574  N74    False           False     0       99
280575  N75    False           False     0       99
280576  N76    False           False     0       99
280577  N77    False           False     0       99
280578  N78    False           False     0       99
280579  N79    False           False     0       99
280580  N80    False           False     0       99
280581  N81    False           False     0       99
280582  N82    False           False     0       99
280583  N83    False           False     0       99
280584  N84    False           False     0       99
280585  N85    False           False     0       99
280586  N86    False           False     0       99
280587  N87    False           False     0       99
280588  N88    False           False     0       99
280589  N89    False           False     0       99
280590  N90    False           False     0       99
280591  N91    False           False     0       99
280592  N92    False           False     0       99
280593  N93    False           False     0       99
280594  N94    False           False     0       99
280595  N95    False           False     0       99
280596  N96    False           False     0       99
280597  N97    False           False     0       99
280598  N98    False           False     0       99
280599  N99    False           False     0       99

[280600 rows x 5 columns]

In [5]:
data["grouped"] = list(zip(data.is_liar, data.is_blacklisted))
grouped_data = data[["node", "grouped"]]

In [6]:
grouped_by_node = grouped_data.groupby("node").agg(lambda x: set(x.values.tolist()))

In [7]:
grouped_by_node["nb_situations"] = grouped_by_node['grouped'].map(lambda x: len(x))

In [8]:
grouped_by_node.sort_values(by="nb_situations", ascending=False)

                             grouped  nb_situations
node
N99   {(False, False), (True, True)}              2
N32   {(False, False), (True, True)}              2
N64   {(False, False), (True, True)}              2
N31   {(False, False), (True, True)}              2
N96                 {(False, False)}              1
N66                 {(False, False)}              1
N74                 {(False, False)}              1
N73                 {(False, False)}              1
N72                 {(False, False)}              1
N71                 {(False, False)}              1
N70                 {(False, False)}              1
N7                    {(True, True)}              1
N69                 {(False, False)}              1
N68                 {(False, False)}              1
N67                 {(False, False)}              1
N65                 {(False, False)}              1
N76                 {(False, False)}              1
N98                 {(False, False)}              1
N63                 {(False, False)}              1
N62                 {(False, False)}              1
N61                 {(False, False)}              1
N60                 {(False, False)}              1
N6                    {(True, True)}              1
N59                 {(False, False)}              1
N58                 {(False, False)}              1
N57                 {(False, False)}              1
N75                 {(False, False)}              1
N77                 {(False, False)}              1
N95                 {(False, False)}              1
N86                 {(False, False)}              1
...                              ...            ...
N14                   {(True, True)}              1
N13                   {(True, True)}              1
N12                   {(True, True)}              1
N11                   {(True, True)}              1
N10                   {(True, True)}              1
N3                    {(True, True)}              1
N30                   {(True, True)}              1
N33                 {(False, False)}              1
N44                 {(False, False)}              1
N52                 {(False, False)}              1
N51                 {(False, False)}              1
N50                 {(False, False)}              1
N5                    {(True, True)}              1
N49                 {(False, False)}              1
N48                 {(False, False)}              1
N47                 {(False, False)}              1
N46                 {(False, False)}              1
N45                 {(False, False)}              1
N43                 {(False, False)}              1
N34                 {(False, False)}              1
N42                 {(False, False)}              1
N41                 {(False, False)}              1
N40                 {(False, False)}              1
N4                    {(True, True)}              1
N39                 {(False, False)}              1
N38                 {(False, False)}              1
N37                 {(False, False)}              1
N36                 {(False, False)}              1
N35                 {(False, False)}              1
N54                 {(False, False)}              1

[100 rows x 2 columns]

In [9]:
data[["node", "is_liar", "is_blacklisted"]].groupby(["is_liar", "is_blacklisted"]).count()

                          node
is_liar is_blacklisted
False   False             6700
True    True            273900

In [10]:
lie_effects = data[["lie", "is_blacklisted"]][data["lie"] > 0]

In [11]:
lie_effects.groupby("lie").count().reset_index()

       lie  is_blacklisted
0     1000             100
1     1001             100
2     1005             200
3     1006             300
4     1007             100
5     1009             100
6     1010             100
7     1019             100
8     1021             100
9     1022             100
10    1023             100
11    1025             100
12    1027             100
13    1028             200
14    1030             100
15    1032             100
16    1033             100
17    1034             200
18    1035             100
19    1036             100
20    1038             200
21    1040             200
22    1042             100
23    1044             200
24    1047             100
25    1049             100
26    1054             100
27    1055             100
28    1057             100
29    1058             100
...    ...             ...
1990  4945             100
1991  4946             100
1992  4948             100
1993  4950             200
1994  4951             200
1995  4952             100
1996  4953             200
1997  4955             200
1998  4956             100
1999  4957             100
2000  4958             100
2001  4959             100
2002  4965             100
2003  4966             100
2004  4967             200
2005  4968             100
2006  4971             200
2007  4972             100
2008  4974             100
2009  4975             200
2010  4978             100
2011  4979             100
2012  4980             200
2013  4986             100
2014  4988             200
2015  4990             100
2016  4994             100
2017  4995             100
2018  4998             200
2019  4999             100

[2020 rows x 2 columns]

In [12]:
lie_effects.groupby("lie").agg(lambda x: set(x.values.tolist())).reset_index().sort_values(by="lie")

       lie is_blacklisted
0     1000         {True}
1     1001         {True}
2     1005         {True}
3     1006         {True}
4     1007         {True}
5     1009         {True}
6     1010         {True}
7     1019         {True}
8     1021         {True}
9     1022         {True}
10    1023         {True}
11    1025         {True}
12    1027         {True}
13    1028         {True}
14    1030         {True}
15    1032         {True}
16    1033         {True}
17    1034         {True}
18    1035         {True}
19    1036         {True}
20    1038         {True}
21    1040         {True}
22    1042         {True}
23    1044         {True}
24    1047         {True}
25    1049         {True}
26    1054         {True}
27    1055         {True}
28    1057         {True}
29    1058         {True}
...    ...            ...
1990  4945         {True}
1991  4946         {True}
1992  4948         {True}
1993  4950         {True}
1994  4951         {True}
1995  4952         {True}
1996  4953         {True}
1997  4955         {True}
1998  4956         {True}
1999  4957         {True}
2000  4958         {True}
2001  4959         {True}
2002  4965         {True}
2003  4966         {True}
2004  4967         {True}
2005  4968         {True}
2006  4971         {True}
2007  4972         {True}
2008  4974         {True}
2009  4975         {True}
2010  4978         {True}
2011  4979         {True}
2012  4980         {True}
2013  4986         {True}
2014  4988         {True}
2015  4990         {True}
2016  4994         {True}
2017  4995         {True}
2018  4998         {True}
2019  4999         {True}

[2020 rows x 2 columns]

In [13]:
bl_by_lie = lie_effects.groupby(['lie', 'is_blacklisted']).size().unstack(fill_value=0).reset_index().sort_values(by="lie")

In [14]:
bl_by_lie

is_blacklisted   lie  True
0               1000   100
1               1001   100
2               1005   200
3               1006   300
4               1007   100
5               1009   100
6               1010   100
7               1019   100
8               1021   100
9               1022   100
10              1023   100
11              1025   100
12              1027   100
13              1028   200
14              1030   100
15              1032   100
16              1033   100
17              1034   200
18              1035   100
19              1036   100
20              1038   200
21              1040   200
22              1042   100
23              1044   200
24              1047   100
25              1049   100
26              1054   100
27              1055   100
28              1057   100
29              1058   100
...              ...   ...
1990            4945   100
1991            4946   100
1992            4948   100
1993            4950   200
1994            4951   200
1995            4952   100
1996            4953   200
1997            4955   200
1998            4956   100
1999            4957   100
2000            4958   100
2001            4959   100
2002            4965   100
2003            4966   100
2004            4967   200
2005            4968   100
2006            4971   200
2007            4972   100
2008            4974   100
2009            4975   200
2010            4978   100
2011            4979   100
2012            4980   200
2013            4986   100
2014            4988   200
2015            4990   100
2016            4994   100
2017            4995   100
2018            4998   200
2019            4999   100

[2020 rows x 2 columns]

In [15]:
bl_by_lie['lie_buckets'] = pd.qcut(bl_by_lie['lie'], 10)

In [16]:
bl_by_lie[["lie_buckets", True, False]].groupby("lie_buckets").sum().reset_index()

KeyError: '[False] not in index'

In [ ]:
fig, ax = plt.subplots(figsize=(20, 10))
bl_by_lie[["lie_buckets", True, False]]\
    .groupby("lie_buckets").sum().reset_index()\
    .plot.bar(stacked=True, ax=ax, rot=0, 
              x="lie_buckets", title="How often a specific lie range got nodes blacklisted")

ax.set_ylabel("Number of times a lie was told by a node and whether that node was blacklisted  over 100 sets, liars random")
ax.set_xlabel("Lie range")

In [ ]:
fig.savefig('graphs/range/'+ filename +".png")

In [ ]:
bl_by_lie["Percentage"] = (bl_by_lie[True]/(bl_by_lie[True] + bl_by_lie[False])).replace([np.inf, -np.inf], 0.0)

In [ ]:
bl_by_lie

In [ ]:
fig1, ax1 = plt.subplots(figsize=(20, 10))
bl_by_lie[["Percentage", "lie_buckets"]]\
    .groupby("lie_buckets").mean().reset_index()\
    .plot(kind="bar",x="lie_buckets", ax=ax1, yticks=[0, 0.2, 0.4, 0.6, 0.8, 1.0],  rot=0,
          title="percentage of nodes telling a given lie that got blacklisted over 100 sets, liars random")

ax1.set_ylabel("Percentage of nodes who told a lie in a given range that got blacklisted")
ax1.set_xlabel("Lie ranges")

In [ ]:
fig1.savefig('graphs/percentage/'+filename+'_percentage.png')